pub const VERSION: &str = env!("CARGO_PKG_VERSION");
pub const SCHEMA_VERSION: u32 = 1;

pub mod agent_detect;
pub mod budget;
pub mod config;
pub mod dispatcher;
pub mod hook_event;
pub mod hooks_merge;
pub mod identity;
pub mod journal;
pub mod lark_cli;
pub mod onboarding;
pub mod paths;
pub mod redact;
pub mod remoterefs;
pub mod rules;
pub mod runaway;
pub mod runners;
pub mod smoke;
pub mod trace;
